[package]
name = "krilla-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-skia-path = {workspace = true}
strict-num = {workspace = true}
pdf-writer = {workspace = true}
once_cell = {workspace = true}
miniz_oxide = {workspace = true}